name: deploy s3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: install
        run: npm ci

      - name: format
        run: npm run format

      # - name: test
      #   run: npm run test

      - name: build
        run: npm run build
        # env:
        #   X_API_KEY: ${{ secrets.X_API_KEY }}
        #   SERVICE_ID: ${{ secrets.SERVICE_ID }}

      - name: deploy file to S3
        run: npm run deploy

      - name: CloudFront Cache Clear
        env:
          CLOUD_FRONT_DISTRIBUTIONS_ID: ${{ secrets.CLOUD_FRONT_DISTRIBUTIONS_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DISTRIBUTIONS_ID --paths "/*"
